=== GaoChengQuan/Java1711Web/src/com/situ/day42/dtd/contactDTD.dtd
<!ELEMENT contactList (contact+)>
<!ELEMENT contact (name,age,phone,email,qq)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT qq (#PCDATA)>

=== GaoChengQuan/Java1711Web/src/com/situ/day42/dtd/contacts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE contacts SYSTEM "contactDTD.dtd">
<contactList>
	<contact>
		<!-- 姓名 -->
		<name>张三</name>
		<age>20</age>
		<phone>2324673264</phone>
		<email>zhangsan@qq.com</email>
		<qq>236823626</qq>
	</contact>
	<contact>
		<name>lisi</name>
		<age>20</age>
		<phone>4545423</phone>
		<email>lisi@qq.com</email>
		<qq>6576878</qq>
	</contact>
</contactList>
